delete from FoodItems;
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Plain Roti", 0, 0.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Butter Roti", 0, 1.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Plain Naan", 0, 3.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Butter Naan", 0, 4.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Garlic Naan", 0, 5.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Vegetable Samosa", 1, 4.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Chicken Samosa", 1, 5.99, 4, 0 );
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Pani Puri", 1, 7.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Bhel Puri", 1, 7.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Vada Pav", 1, 7.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Vegetable Biryani", 2, 10.99, 6, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Chicken Biryani", 2, 12.99, 6, 0);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Palak Paneer", 2, 9.99, 6, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Shahi Paneer", 2, 9.99, 6, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Mattar Paneer", 2, 9.99, 6, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Paneer Bhurji", 2, 9.99, 5, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Egg Bhurji", 2, 9.99, 5, 0);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Navratna Korma", 2, 9.99, 6, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Butter Chicken", 2, 11.99, 7, 0);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Chicken Do Pyaza", 2, 11.99, 7, 0);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Dal Tadka", 2, 7.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Dal Moong", 2, 7.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Dal Makhani", 2, 8.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Pav Bhaji", 2, 9.99, 5, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Aloo Gobhi", 2, 7.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Aloo Bainghan", 2, 7.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Bhindi Fry", 2, 7.99, 5, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Masala Dosa", 2, 9.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Onion Uttapam", 2, 9.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Idli Sambhar", 2, 8.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Fish Curry", 2, 9.99, 6, 0);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Dhahi Bhalla", 3, 6.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Gulab Jamun", 3, 6.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Rasmalai", 3, 6.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Rasgulla", 3, 6.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Sewaiyan", 3, 7.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Plain Chai", 4, 3.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Masala Chai", 4, 4.99, 4, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Cardamom Chai", 4, 4.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Sweet Lassi", 4, 5.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Salty Lassi", 4, 5.99, 0, 1);
insert into FoodItems (Name, Category, Price, SpiceLevel, IsVegetarian) values("Coffee", 4, 3.99, 0, 1 );
